services:
  serv1:
    image: alpine
    command: tail -f /dev/null
  serv2:
    image: alpine
    command: tail -f /dev/null
  serv3:
    image: alpine
    command: tail -f /dev/null
    scale: 2
  serv4:
    image: nginx
    volumes:
      - nginx_volume:/usr/share/nginx/html

volumes:
  nginx_volume:
